// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BinAggregatingEndpoint.proto

package org.locationtech.geomesa.hbase.proto;

public final class BinAggregatingProto {
  private BinAggregatingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BinAggregatingRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BinAggregatingRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes options = 1;</code>
     */
    boolean hasOptions();
    /**
     * <code>required bytes options = 1;</code>
     */
    com.google.protobuf.ByteString getOptions();
  }
  /**
   * Protobuf type {@code BinAggregatingRequest}
   */
  public static final class BinAggregatingRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BinAggregatingRequest)
      BinAggregatingRequestOrBuilder {
    // Use BinAggregatingRequest.newBuilder() to construct.
    private BinAggregatingRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BinAggregatingRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BinAggregatingRequest defaultInstance;
    public static BinAggregatingRequest getDefaultInstance() {
      return defaultInstance;
    }

    public BinAggregatingRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BinAggregatingRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              options_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.locationtech.geomesa.hbase.proto.BinAggregatingProto.internal_static_BinAggregatingRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.locationtech.geomesa.hbase.proto.BinAggregatingProto.internal_static_BinAggregatingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest.class, org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<BinAggregatingRequest> PARSER =
        new com.google.protobuf.AbstractParser<BinAggregatingRequest>() {
      public BinAggregatingRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BinAggregatingRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BinAggregatingRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int OPTIONS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString options_;
    /**
     * <code>required bytes options = 1;</code>
     */
    public boolean hasOptions() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes options = 1;</code>
     */
    public com.google.protobuf.ByteString getOptions() {
      return options_;
    }

    private void initFields() {
      options_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOptions()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, options_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, options_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest)) {
        return super.equals(obj);
      }
      org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest other = (org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest) obj;

      boolean result = true;
      result = result && (hasOptions() == other.hasOptions());
      if (hasOptions()) {
        result = result && getOptions()
            .equals(other.getOptions());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasOptions()) {
        hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getOptions().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BinAggregatingRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BinAggregatingRequest)
        org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.locationtech.geomesa.hbase.proto.BinAggregatingProto.internal_static_BinAggregatingRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.locationtech.geomesa.hbase.proto.BinAggregatingProto.internal_static_BinAggregatingRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest.class, org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest.Builder.class);
      }

      // Construct using org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        options_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.locationtech.geomesa.hbase.proto.BinAggregatingProto.internal_static_BinAggregatingRequest_descriptor;
      }

      public org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest getDefaultInstanceForType() {
        return org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest.getDefaultInstance();
      }

      public org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest build() {
        org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest buildPartial() {
        org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest result = new org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.options_ = options_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest) {
          return mergeFrom((org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest other) {
        if (other == org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest.getDefaultInstance()) return this;
        if (other.hasOptions()) {
          setOptions(other.getOptions());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOptions()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString options_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes options = 1;</code>
       */
      public boolean hasOptions() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes options = 1;</code>
       */
      public com.google.protobuf.ByteString getOptions() {
        return options_;
      }
      /**
       * <code>required bytes options = 1;</code>
       */
      public Builder setOptions(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        options_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes options = 1;</code>
       */
      public Builder clearOptions() {
        bitField0_ = (bitField0_ & ~0x00000001);
        options_ = getDefaultInstance().getOptions();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BinAggregatingRequest)
    }

    static {
      defaultInstance = new BinAggregatingRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BinAggregatingRequest)
  }

  public interface BinAggregatingResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BinAggregatingResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes bin_feature = 1;</code>
     */
    boolean hasBinFeature();
    /**
     * <code>required bytes bin_feature = 1;</code>
     */
    com.google.protobuf.ByteString getBinFeature();
  }
  /**
   * Protobuf type {@code BinAggregatingResponse}
   */
  public static final class BinAggregatingResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BinAggregatingResponse)
      BinAggregatingResponseOrBuilder {
    // Use BinAggregatingResponse.newBuilder() to construct.
    private BinAggregatingResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BinAggregatingResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BinAggregatingResponse defaultInstance;
    public static BinAggregatingResponse getDefaultInstance() {
      return defaultInstance;
    }

    public BinAggregatingResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BinAggregatingResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              binFeature_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.locationtech.geomesa.hbase.proto.BinAggregatingProto.internal_static_BinAggregatingResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.locationtech.geomesa.hbase.proto.BinAggregatingProto.internal_static_BinAggregatingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse.class, org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<BinAggregatingResponse> PARSER =
        new com.google.protobuf.AbstractParser<BinAggregatingResponse>() {
      public BinAggregatingResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BinAggregatingResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BinAggregatingResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BIN_FEATURE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString binFeature_;
    /**
     * <code>required bytes bin_feature = 1;</code>
     */
    public boolean hasBinFeature() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes bin_feature = 1;</code>
     */
    public com.google.protobuf.ByteString getBinFeature() {
      return binFeature_;
    }

    private void initFields() {
      binFeature_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBinFeature()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, binFeature_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, binFeature_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse)) {
        return super.equals(obj);
      }
      org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse other = (org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse) obj;

      boolean result = true;
      result = result && (hasBinFeature() == other.hasBinFeature());
      if (hasBinFeature()) {
        result = result && getBinFeature()
            .equals(other.getBinFeature());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasBinFeature()) {
        hash = (37 * hash) + BIN_FEATURE_FIELD_NUMBER;
        hash = (53 * hash) + getBinFeature().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BinAggregatingResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BinAggregatingResponse)
        org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.locationtech.geomesa.hbase.proto.BinAggregatingProto.internal_static_BinAggregatingResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.locationtech.geomesa.hbase.proto.BinAggregatingProto.internal_static_BinAggregatingResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse.class, org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse.Builder.class);
      }

      // Construct using org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        binFeature_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.locationtech.geomesa.hbase.proto.BinAggregatingProto.internal_static_BinAggregatingResponse_descriptor;
      }

      public org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse getDefaultInstanceForType() {
        return org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse.getDefaultInstance();
      }

      public org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse build() {
        org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse buildPartial() {
        org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse result = new org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.binFeature_ = binFeature_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse) {
          return mergeFrom((org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse other) {
        if (other == org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse.getDefaultInstance()) return this;
        if (other.hasBinFeature()) {
          setBinFeature(other.getBinFeature());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBinFeature()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString binFeature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes bin_feature = 1;</code>
       */
      public boolean hasBinFeature() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes bin_feature = 1;</code>
       */
      public com.google.protobuf.ByteString getBinFeature() {
        return binFeature_;
      }
      /**
       * <code>required bytes bin_feature = 1;</code>
       */
      public Builder setBinFeature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        binFeature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes bin_feature = 1;</code>
       */
      public Builder clearBinFeature() {
        bitField0_ = (bitField0_ & ~0x00000001);
        binFeature_ = getDefaultInstance().getBinFeature();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BinAggregatingResponse)
    }

    static {
      defaultInstance = new BinAggregatingResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BinAggregatingResponse)
  }

  /**
   * Protobuf service {@code BinAggregatingService}
   */
  public static abstract class BinAggregatingService
      implements com.google.protobuf.Service {
    protected BinAggregatingService() {}

    public interface Interface {
      /**
       * <code>rpc getBinQuery(.BinAggregatingRequest) returns (.BinAggregatingRequest);</code>
       */
      public abstract void getBinQuery(
          com.google.protobuf.RpcController controller,
          org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest request,
          com.google.protobuf.RpcCallback<org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new BinAggregatingService() {
        @java.lang.Override
        public  void getBinQuery(
            com.google.protobuf.RpcController controller,
            org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest request,
            com.google.protobuf.RpcCallback<org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest> done) {
          impl.getBinQuery(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getBinQuery(controller, (org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getBinQuery(.BinAggregatingRequest) returns (.BinAggregatingRequest);</code>
     */
    public abstract void getBinQuery(
        com.google.protobuf.RpcController controller,
        org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest request,
        com.google.protobuf.RpcCallback<org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.locationtech.geomesa.hbase.proto.BinAggregatingProto.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getBinQuery(controller, (org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest)request,
            com.google.protobuf.RpcUtil.<org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getBinQuery(
          com.google.protobuf.RpcController controller,
          org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest request,
          com.google.protobuf.RpcCallback<org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest.class,
            org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest getBinQuery(
          com.google.protobuf.RpcController controller,
          org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest getBinQuery(
          com.google.protobuf.RpcController controller,
          org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.locationtech.geomesa.hbase.proto.BinAggregatingProto.BinAggregatingRequest.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:BinAggregatingService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BinAggregatingRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BinAggregatingRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BinAggregatingResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BinAggregatingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034BinAggregatingEndpoint.proto\"(\n\025BinAgg" +
      "regatingRequest\022\017\n\007options\030\001 \002(\014\"-\n\026BinA" +
      "ggregatingResponse\022\023\n\013bin_feature\030\001 \002(\0142" +
      "V\n\025BinAggregatingService\022=\n\013getBinQuery\022" +
      "\026.BinAggregatingRequest\032\026.BinAggregating" +
      "RequestBC\n$org.locationtech.geomesa.hbas" +
      "e.protoB\023BinAggregatingProtoH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BinAggregatingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BinAggregatingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BinAggregatingRequest_descriptor,
        new java.lang.String[] { "Options", });
    internal_static_BinAggregatingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BinAggregatingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BinAggregatingResponse_descriptor,
        new java.lang.String[] { "BinFeature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
